# Site settings
title: Introduction to Programming with Julia
description: "Introduction to Programming with Julia"
contactmessage: "We value your feedback:"   # Call to action message in the footer
surveyurl: "http://goo.gl/d7bwux"           # The URL of a feedback or interest survey
email: training@intersect.org.au            # Your email contact address
licence: "All content on this site is copyright (c) of Intersect Australia Ltd 2018. All rights reserved"      # A statement of the licencing conditions of your site
baseurl: "/Introduction-to-programming-with-julia" # the subpath of your site, e.g. /blog
url: "https://intersectaustralia.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: "IntersectAustralia/intersect-training-theme"
markdown: kramdown
permalink: pretty
highlighter: rouge
